package com.mugheadgolf.app.navigation

object Routes {
    const val SIGN_IN = "signin"
    const val FORGOT = "forgot"
    const val REGISTER = "register/{id}"
    const val REGISTER_RESPONSE = "registerResponse"
    const val ACTIVATION_NOTICE = "activationNotice"
    const val AUTHENTICATE = "authenticate/{token}"
    const val TUTORIAL = "tutorial"
    const val TUTORIAL_TEE_TIMES = "tutorialTeeTimes"
    const val DASHBOARD = "dashboard"
    const val GOLFERS = "golfers"
    const val HANDICAPS = "handicaps"
    const val WEEKLY_SCHEDULE = "weeklySchedule"
    const val GOLFER_SCHEDULE = "golferSchedule"
    const val FOURSOMES = "foursomes"
    const val CREATE_SCHEDULE = "createSchedule"
    const val MATCH = "match/{idschedule}"
    const val FOURSOME_SCORE = "foursomeScore/{idfoursome}"
    const val WEEKLY_SCORES = "weeklyScores"
    const val GOLFER_SCORES = "golferScores"
    const val GOLFER_NET_SCORES = "golferNetScores"
    const val EDIT_SCORE = "editScore"
    const val STANDINGS = "standings"
    const val STATS = "stats"
    const val WEEKLY_STATS = "weeklyStats"
    const val GOLFER_MONEY = "golferMoney"
    const val WEEKLY_MONEY = "weeklyMoney"
    const val ADD_WINNERS = "addWinners"
    const val TOURNEY_LOW = "tourneyLow"
    const val TOURNEY_HIGH = "tourneyHigh"
    const val TOURNEY_NET = "tourneyNet"
    const val BRACKET_LOW = "bracketLow"
    const val BRACKET_HIGH = "bracketHigh"
    const val WAGER = "wager"
    const val WAGER_RESULTS = "wagerResults"
    const val FOOD = "food"
    const val ORDER = "order"
    const val YEAR = "year"
    const val CALC_HANDICAPS = "calcHandicaps"
    const val ADD_GOLFER = "addGolfer/{id}"
    const val EDIT_GOLFER = "editGolfer"
    const val DIVISION_SETUP = "divisionSetup"
    const val DIVISION = "division"
    const val SETTINGS = "settings"
    const val EMAIL = "email"
    const val SEND_SCHEDULE = "sendSchedule"

    fun register(id: String) = "register/$id"
    fun authenticate(token: String) = "authenticate/$token"
    fun match(idschedule: Int) = "match/$idschedule"
    fun foursomeScore(idfoursome: Int) = "foursomeScore/$idfoursome"
    fun addGolfer(id: Int) = "addGolfer/$id"
}
